name: test

on:
  push:
    branches: [main, feat/more-actions-options]
  pull_request:
    branches: [main]

jobs:
  test:
    name: test-action
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Deploy to Deno Deploy
        uses: ./
        with:
          project: fat-starling-37
          root: action/tests
          entrypoint: hello.ts
          import-map: ./import_map.json
